---
title: Prediksi Hk Mbah Semar
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: 
    share: true
    related: true
minimal_mistakes_skin: default
locale: en-US
title_separator: "-"
subtitle: 
name: Prediksi Hk Mbah Semar
description: Prediksi Hk Mbah Semar.
url: 
baseurl: https://prediksi.hkmbahsemar.me/
repository: https://github.com/cobasemarmesem/minimal-mistakes
teaser: 
logo: "/uploads/HK-MBAH-SEMAR.png"
masthead_title: 
words_per_minute: 200
enable_copy_code_button: 
copyright: 
copyright_url: 
comments:
  provider: 
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
  utterances:
    theme: 
    issue_term: 
  giscus:
    repo_id: 
    category_name: 
    category_id: 
    discussion_term: 
    reactions_enabled: 
    theme: 
    strict: 
    input_position: 
    emit_metadata: 
    lang: 
    lazy: 
  staticman:
    branch: 
    endpoint: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
  hide: 
search: 
search_full_content: 
search_provider: 
lunr:
  search_within_pages: 
algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: 
google:
  search_engine_id: 
  instant_search: 
google_site_verification: 
bing_site_verification: 
naver_site_verification: 
yandex_site_verification: 
baidu_site_verification: 
twitter:
  username: 
facebook:
  username: 
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: 
author:
  name: Hk Mbah Semar
  avatar: 
  bio: Prediksi Hk Mbah Semar Akurat
  location: Indonesia
  email: megafitria297@gmail.com
  links:
  - label: Email
    icon: fas fa-fw fa-envelope-square
  - label: Website
    icon: fas fa-fw fa-link
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- package-lock.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
pagination:
  debug: false
  collection: posts
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: 
  locale: 
  trail:
    before: 2
    after: 2
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jekyll-include-cache
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
